### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by fractalysid** [nikosl21/Gen2-UHF-RFID-Reader#27]
Hello,
I tried compiling the program but I get these two kind of errors:

> gr-rfid/lib/gate_impl.cc:36:9:  error: could not convert 'gnuradio::get_initial_sptr(T*) [with T = gr::rfid::gate_impl]()' from 'std::shared_ptr<gr::rfid::gate_impl>' to 'gr::rfid::gate::sptr' {aka 'boost::shared_ptr<gr::rfid::gate>'}
   35 |       return gnuradio::get_initial_sptr
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~
   36 |         (new gate_impl(sample_rate));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         |
      |         std::shared_ptr<gr::rfid::gate_impl>

and
> gr-rfid/lib/gate_impl.cc:58:45: error: invalid operands of types 'const char [14]' and 'int' to binary 'operator<<'
   58 |       GR_LOG_INFO(d_logger, "T1 samples : " << n_samples_T1);
      |                             ~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~
      |                             |                  |
      |                             const char [14]    int

Completely in the dark about the first one. While regarding the second one, for what I can remember about C++, that was not  a valid syntax for concatenating strings (at least before C++11).

I tested it on Fedora 27, Ubuntu 22.04 and Gentoo. Same errors.
GCC 12.3 and Gnuradio 3.10.6 (on Gentoo).

Any idea?

Thank you in advance

**Comment by LdBeth** [comment]
You are right about the missing << operator.

after gnuradio 3.9 several breaking changes has been made, see https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide

I’m trying to make the port so that this can work on gnuradio 3.10, if anyone has also made progress please let me know.

**Comment by vhenmo** [comment]
> You are right about the missing << operator.
> 
> after gnuradio 3.9 several breaking changes has been made, see https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide
> 
> I’m trying to make the port so that this can work on gnuradio 3.10, if anyone has also made progress please let me know.

Hello! Did you successfully port this project to GNU Radio 3.10? I’ve also been attempting the migration recently but have encountered some difficulties.

**Comment by LdBeth** [comment]
@vhenmo Sorry but my focus has been shifted since then so I have not made progress in porting.

**Comment by vhenmo** [comment]
@LdBeth  OK, thank you for your response!
