### ISSUE TITLE
issue it works with gnuradio 3.7.2 but for other version 3.8.1 and ....can not compiled 

### ISSUE THREAD

**Issue by stackprogramer** [nikosl21/Gen2-UHF-RFID-Reader#26]
when I want to compile for Gnuradio 3.8.1 I faced this error...
 error: invalid operands of types ‘const char [14]’ and ‘int’ to binary ‘operator<<’
   58 |       GR_LOG_INFO(d_logger, "T1 samples : " << n_samples_T1);
      |                             ~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~
      |                             |                  |
      |                             const char [14]    int
/home/sp/Documents/Gen2-UHF-RFID-Reader-master/gr-rfid/lib/gate_impl.cc:59:45: error: invalid operands of types ‘const char [14]’ and ‘int’ to binary ‘operator<<’
   59 |       GR_LOG_INFO(d_logger, "PW samples : " << n_samples_PW);
      |                             ~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~
      |                             |                  |

**Comment by dd7272** [comment]
I run into the same problem, with ubuntu20.04 uhd 3.15.0.0 and gnuradio 3.8.1. Did you find out why?

**Comment by Yulong97** [comment]
I believe the issue arises because Gnuradio version 3.8 or later is not compatible with Python 2, etc. 

>We suggest, you adapt a similar model in your OOT. That means your maint-3.8 branch is compatible with GNU Radio maint-3.8 and your master branch is compatible GNU Radio master. Trying to maintain a single branch that works with all future, present, and past versions of GNU Radio versions is mess and you’d have to differentiate between too many cases (API changes, XML vs YAML GRC bindings, Python 2 vs 3, QT4 vs QT5, log4cpp support or not, CPPUnit or Boost unit tests, etc.).
(https://wiki.gnuradio.org/index.php?title=GNU_Radio_3.8_OOT_Module_Porting_Guide)
